### ISSUE TITLE
`+`の挙動の修正

### ISSUE THREAD

**Issue by blue031415** [kitagawahiroto/git-training-10#1]
## 操作手順
* `+`を選択したら減算になった。

## 本来の想定
* `+`を選択したら加算が実行されて欲しい。

## 操作環境
* OS: windows11 Home
* OSバージョン: 23H2
* ブラウザ: Google Chrome
* ブラウザバージョン: 128.0.6613.138

**Comment by sagi5491** [comment]
v0.1で修正された

**Comment by sagi5491** [comment]
間違えました
