### ISSUE TITLE
小数点切り上げの挙動の修正

### ISSUE THREAD

**Issue by sagagas** [kitagawahiroto/git-training-10#3]
## 操作手順
小数点の掛け算の結果を小数点切り上げにしたにも関わらず、小数点切り捨てになってしまう。

## 本来の想定
小数点の結果は小数点切り上げにしたら、小数点切り上げになる。

## 操作環境
* OS　Mac
* ブラウザ　Chrome

**Comment by blue031415** [comment]
修正確認済み
